{% set name = "calkulate" %}
{% set version = "23.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/calkulate-{{ version }}.tar.gz
  sha256: f30d929c14fb1266c72855e2c560a5b6cf1bbddf4b6a3bdc99f6844261b260fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - pyco2sys
    - matplotlib-base
    - numpy
    - openpyxl
    - pandas
    - scipy

test:
  imports:
    - calkulate
  commands:
    - pip check
  requires:
    - pip

about:
  summary: 'Calkulate: seawater total alkalinity from titration data'
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/calkulate

extra:
  recipe-maintainers:
    - mvdh7
